### PR TITLE
DOM.Simple.Types.IsElement instance for react Element

### PR DESCRIPTION
**Pull request by CGenie**

### CODE REVIEW

**Comment by jjl** [comment]
really?

**Comment by CGenie** [comment]
I'm trying things out, guess shouldn't have merged to master, will revert.

**Comment by jjl** [comment]
i can see some reasons why it might be desirable. what were you trying to do?

**Comment by CGenie** [comment]
I need to compute bounding box for child elements. I guess I should find a `Reactix.Element -> DOM.Simple.Element.Element` conversion instead.

**Comment by jjl** [comment]
not sure how you'd do that from a Reactix.Element? surely you want to pass a ref and access the actual  element?

**Comment by CGenie** [comment]
https://gitlab.iscpif.fr/gargantext/purescript-gargantext/blob/aedbeb2740faf83e89a2e65b85e5592a2d08f68a/src/Gargantext/Components/ContextMenu/ContextMenu.purs#L34-43
I need the boundingRect computed from child elements. This is so that the menu rectangle is set properly. Is this even possible to do it like this?

**Comment by jjl** [comment]
can you not do it with css??

**Comment by CGenie** [comment]
https://gitlab.iscpif.fr/gargantext/purescript-gargantext/blob/aedbeb2740faf83e89a2e65b85e5592a2d08f68a/src/Gargantext/Components/ContextMenu/ContextMenu.purs#L102-109
`ContextMenu` needs to compute its position based on given `x`, `y` values and children's `width`/`height`.

**Comment by jjl** [comment]
i'm not sure if there's a *good* way to do this, but here's *a* way...

render them twice. once invisibly for measuring, the second time for real

**Comment by jjl** [comment]
oh, is this the intended purpose of the mysterious [useImperativeHandle](https://reactjs.org/docs/hooks-reference.html#useimperativehandle) ?

**Comment by orther** [comment]
https://github.com/ctrlplusb/react-sizeme

**Comment by orther** [comment]
So I'm lost in the PureScript so I'll simple answer about useImparativeHandler... If you want to _implement_ your own component that provides custom values on ref for parent components to read then yeah `useImpartiaveHandler` is what you would use but I don't know if that brings you much value in this scenario.

As you mentioned, you'd need to render "invisible" initially to get the width/height before the content is shown on screen. The lib https://github.com/souporserious/react-measure implements this invisible first render and measure and could potentially be a good reference if not just using it directly.

**Comment by jjl** [comment]
thanks @orther, glad to hear there isn't a better approach

**Pull request merged**
